In [1]:
## PYTHON NUMPY

# NDARRAY : 1D array : une liste ==> ndim = 1 shape =(2,) ==> 1 colonne
            #2D array : une page excel pour stocker les pixels d'une image => ndim = 2 shape 
                # ==>(2, 3)=> 2 haute 3 lgn ==> c'est un TUPLE
            #3D array : un cube ... ==> ndim = 3 shape =(2, 3, 2) ==> 2 hauteur, 3 lgn et 2 profondeur
        
# l'attribut SHAPE permet de voir la forme du tableau : sa couleur, sa profondeur...

# c'est aussi un tuple ()
# shape = (2, 3) : 3 col et 2 lignes ==> shape[0] = 2 et shape [1] = 3   


In [2]:
import numpy as np
np.array([1, 2, 3])

array([1, 2, 3])

In [5]:
import numpy as np
A = np.array([1, 2, 3])

# nb de dimension ?
A.ndim


1

In [6]:
# combien d'éléments :

A.shape

(3,)

In [7]:

A.size

3

In [8]:
# Une autre façon de construire son tableau :

B = np.zeros((3, 2)) # ==> 3 lignes et 2 colonnes
B


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
B.ndim


2

In [10]:

B.shape

(3, 2)

In [11]:
type(B.shape)

tuple

In [12]:
C = np.ones((3, 4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
# taille du tablo :
    
C.size    

12

In [14]:
D = np.full((2, 3), 9)
D

array([[9, 9, 9],
       [9, 9, 9]])

In [17]:
np.random.randn(3, 4) # ce n'est pas un tuple

# avec des chiffres aléatoires issus de la distribution normale

array([[-0.70438975,  0.21779875, -0.17824081,  0.00905973],
       [ 0.36688091,  0.79649629,  0.0581367 ,  0.82582018],
       [ 0.14365869,  1.91203465,  0.61027993,  1.58070556]])

In [18]:
import numpy as np

#np.random.seed(0)
# = np.random.seed(1)
#np.random.seed(5)
#np.random.seed(312098)


# distribution normale : 
np.random.randn(3, 4)

#np.random.rand(3, 4)


array([[ 0.27873321,  1.33642221, -0.68976022,  0.4270193 ],
       [ 0.94179734,  0.26262941, -0.84797748,  0.27649201],
       [-0.75839751,  1.27865307, -0.51850919,  0.4263763 ]])

In [19]:
# matrice identité 

np.eye(4) # 4 lignes et 4 colonnes

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.linspace(0, 10, 20) # 20 chiffres qui vont de 0 à 10

# création d'un tableau à 1 dimension

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [21]:
np.linspace(5, 10, 20) # 20 chiffres qui vont de 0 à 10

array([ 5.        ,  5.26315789,  5.52631579,  5.78947368,  6.05263158,
        6.31578947,  6.57894737,  6.84210526,  7.10526316,  7.36842105,
        7.63157895,  7.89473684,  8.15789474,  8.42105263,  8.68421053,
        8.94736842,  9.21052632,  9.47368421,  9.73684211, 10.        ])

In [11]:
np.arange(0, 10, 1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0, 10, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [16]:
np.linspace(0, 10, 20, dtype = np.float64 ) # 20 chiffres qui vont de 0 à 10

# hc élément occupe 64 bites sur la mémoire et donc sera plus précis mais plus lent par ex que float16

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [19]:
np.linspace(0, 10, 20) # 20 chiffres qui vont de 0 à 10

print(A)
print(B)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [25]:
# les assembler de façon horizontale

C = np.hstack((A, B))
C



array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [24]:
C. shape

(3, 4)

In [26]:
C = np.vstack((A, B))
C

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [27]:
C. shape

(6, 2)

In [28]:
# une autre methode :

np.concatenate((A, B))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
np.concatenate((A, B), axis = 0) # ==> pareil que concatenate simple ou vstack

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [30]:
np.concatenate((A, B), axis = 1) # ==> pareil que hstack

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [33]:
#  1 pour remanipuler un tablo et lui donner une nouvelle forme :

C.size

12

In [37]:
 # 2

C.shape
C

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
# 3

D = C.reshape((3, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
# 1

E = np.array([1, 2, 3])
E.shape

(3,)

In [42]:
# 2

E = np.array([1, 2, 3])
E = E.reshape((A.shape[0], 1))
E.shape


(3, 1)

In [44]:
# 3

E = E.squeeze()
E.shape

(3,)

In [45]:
# 1 pour mettre le tableau sur une dimension
D.shape
D

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
# 2

D.ravel().shape # ravel pour applatir le tableau sur une seule dimension

(12,)

In [1]:
# EXO

import numpy as np

def initialisation (m, n) :
    # m : nb de lignes
    # n : nb de colonnes
    # retourne une matrice aléatoire(m, n+1)
    # avec une colonne biais (remplie de "1") tout à droite
    
    return 



In [43]:
n = 1
tablo_1 = np.eye(3)
tablo_1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
m = 2
n = 2

tablo_2 = np.random.randn(m, n+1)
tablo_2



array([[-1.52124514,  0.22022063, -0.4453508 ],
       [ 1.54068444,  0.0913573 ,  1.70724214]])

In [22]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])