In [ ]:
# LIEN VERS LES DOCUMENTATIONS:

# Numpy ndarray
# https://docs.scipy.org/doc/numpy/refe...

# Numpy fonctions mathématiques
# https://docs.scipy.org/doc/numpy-1.13...

# Numpy statistiques
# https://docs.scipy.org/doc/numpy-1.13...

# Numpy algèbre Linéaire
# https://docs.scipy.org/doc/numpy-1.13...

# Wikipédia Normalisation et Standardisation
# https://en.wikipedia.org/wiki/Feature..

In [1]:
import numpy as np

In [8]:
np.random.seed(0)
A = np.random.randint(0, 10, [2, 3])# des chiffres de 0 à 10 dans un tablo avec 2 lignes et 3 colonnes
A

array([[5, 0, 3],
       [3, 7, 9]])

In [13]:
A.sum()

27

In [12]:
A.sum(axis= 0) # addition de toutes les colonnes

array([ 8,  7, 12])

In [6]:
A.sum(axis= 1) # addition de toutes les lignes

array([ 8, 19])

In [14]:
A.cumsum() # 5+ 0 +3 +3 +7 +9

array([ 5,  5,  8, 11, 18, 27])

In [15]:
A.mean() # moyenne

4.5

In [17]:
np.corrcoef(A) # matrice de corrélation

array([[ 1.        , -0.56362148],
       [-0.56362148,  1.        ]])

In [18]:
np.corrcoef(A) [0, 1]

-0.563621480190678

In [20]:
np.unique(A, return_counts= True) # combien de fois apparaissent les chiffres ?

(array([0, 3, 5, 7, 9]), array([1, 2, 1, 1, 1]))

In [21]:
values, counts = np.unique(A, return_counts= True)

In [23]:
counts

array([1, 2, 1, 1, 1])

In [24]:
counts.argsort()

array([0, 2, 3, 4, 1])

In [25]:
values [counts.argsort()]

array([0, 5, 7, 9, 3])

In [28]:
for i, j in zip(values [counts.argsort()], counts[counts.argsort()]) :
    print(f'valeur {i} apparait {j}') #f = format

valeur 0 apparait 1
valeur 5 apparait 1
valeur 7 apparait 1
valeur 9 apparait 1
valeur 3 apparait 2
